### ISSUE TITLE
【Documentation】 shield of resistance: additional resistance type

### ISSUE THREAD

**Issue by backwardsEric** [hengband/hengband#412]
## 環境

- OS: Any
- バージョン: 3.0.0Alpha8

## バグの詳細

Google Translate's result for the description of shields of resistance in jdefend.txt, lines 166 - 169, implies that the shield can have an additional random resistance.  However, from what I see in lib/edit/e_info.txt and in src/object-enchant/apply-magic.c and src/object-enchant/apply-magic-armor.c, there's no additional resistance applied to such a shield when it is created.

**Comment by iks3** [comment]
Hi, thank you for your report.

I confirmed that the description is not wrong by reviewing codes and using wizerd commands of 変愚蛮怒.

Ego 'of Resistance' of shields is defined as No.20 in e_info.txt
and is defined as macro value 'EGO_ENDURANCE' in src/object-enchant/object-ego.h
because 'of Resistance' of armors is already defined as 'EGO_RESISTANCE' .

See at line 184-189 in src/object-enchant/apply-magic-armor.c ,
when the object's ego index is EGO_ENDURANCE which is a shield of resistance,
it will get 1 extra high resistance in 1/3 and poison resistance additionaly in 1/4 .

**Comment by backwardsEric** [comment]
Okay, so it's my code reading abilities that are the issue.  I'll close this.
